site_name: 厦门大学·RoboMaster·硬件标准化
site_favicon: favicon.ico
site_url: https://xmu-rm-hwsd-um.readthedocs.io/en/latest/
nav:
- Overview:
    - Introduction: Introduction.md
    - About this document: About-this-document.md
- ACTR Series:
    - H-bridge: H-bridge.md
    - High-Side Switch: High-Side-Switch.md
- Adapter Series:
    - CAN Center: CAN-Center.md
    - CAN Cube: CAN-Cube.md
    - DBUS: DBUS.md
    - GH2GH: GH2GH.md
    - XT2XT: XT2XT.md
- Assistant Series:
    - WiFi: WiFi.md
- MAIN Series:
    - Core: Core.md
    - Robotics: Robotics.md
- PSM Series:
    - POL: POL.md
- SNSR Series:
    - Gyroscope: Gyroscope.md
- Toolkit Series: 
    - DAPLink: DAPLink.md
    - Detector: Detector.md
    - USB2TTL: USB2TTL.md
- Support:
    - Software Support: Software-Support.md
    - Application Case: Application-Case.md
    - Infrastructure: Infrastructure.md
    - Model Download: Model-Download.md
    
theme: readthedocs
site_author: ASR-Crash
copyright: Copyright © 2021 ASR-Crash <img src='ASR-ico.ico' width='64'> | &nbsp;<img src='Crash-precision.png' width='160'>